export const INBOUND_CREATE_REQUEST = 'INBOUND_CREATE_REQUEST'
export const INBOUND_CREATE_SUCCESS = 'INBOUND_CREATE_SUCCESS'
export const INBOUND_CREATE_FAIL = 'INBOUND_CREATE_FAIL'
export const INBOUND_CREATE_RESET = 'INBOUND_CREATE_RESET'


export const INBOUND_LIST_REQUEST = 'INBOUND_LIST_REQUEST'
export const INBOUND_LIST_SUCCESS = 'INBOUND_LIST_SUCCESS'
export const INBOUND_LIST_FAIL = 'INBOUND_LIST_FAIL'