export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST'
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS'
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL'
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST'
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS'
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL'
export const ORDER_DELETE_RESET = 'ORDER_DELETE_RESET'

export const ORDER_APPROVE_REQUEST = 'ORDER_APPROVE_REQUEST'
export const ORDER_APPROVE_SUCCESS = 'ORDER_APPROVE_SUCCESS'
export const ORDER_APPROVE_FAIL = 'ORDER_APPROVE_FAIL'
export const ORDER_APPROVE_RESET = 'ORDER_APPROVE_RESET'

export const ORDER_FINANCEAPPROVE_REQUEST = 'ORDER_FINANCEAPPROVE_REQUEST'
export const ORDER_FINANCEAPPROVE_SUCCESS = 'ORDER_FINANCEAPPROVE_SUCCESS'
export const ORDER_FINANCEAPPROVE_FAIL = 'ORDER_FINANCEAPPROVE_FAIL'
export const ORDER_FINANCEAPPROVE_RESET = 'ORDER_FINANCEAPPROVE_RESET'

export const ORDER_FINALAPPROVE_REQUEST = 'ORDER_FINALAPPROVE_REQUEST'
export const ORDER_FINALAPPROVE_SUCCESS = 'ORDER_FINALAPPROVE_SUCCESS'
export const ORDER_FINALAPPROVE_FAIL = 'ORDER_FINALAPPROVE_FAIL'
export const ORDER_FINALAPPROVE_RESET = 'ORDER_FINALAPPROVE_RESET'

export const ORDER_REJECT_REQUEST = 'ORDER_REJECT_REQUEST'
export const ORDER_REJECT_SUCCESS = 'ORDER_REJECT_SUCCESS'
export const ORDER_REJECT_FAIL = 'ORDER_REJECT_FAIL'
export const ORDER_REJECT_RESET = 'ORDER_REJECT_RESET'