export const MANUFACTURER_LIST_REQUEST = 'MANUFACTURER_LIST_REQUEST'
export const MANUFACTURER_LIST_SUCCESS = 'MANUFACTURER_LIST_SUCCESS'
export const MANUFACTURER_LIST_FAIL = 'MANUFACTURER_LIST_FAIL'

export const MANUFACTURER_CREATE_REQUEST = 'MANUFACTURER_CREATE_REQUEST'
export const MANUFACTURER_CREATE_SUCCESS = 'MANUFACTURER_CREATE_SUCCESS'
export const MANUFACTURER_CREATE_FAIL = 'MANUFACTURER_CREATE_FAIL'
export const MANUFACTURER_CREATE_RESET = 'MANUFACTURER_CREATE_RESET'

export const MANUFACTURER_DELETE_REQUEST = 'MANUFACTURER_DELETE_REQUEST'
export const MANUFACTURER_DELETE_SUCCESS = 'MANUFACTURER_DELETE_SUCCESS'
export const MANUFACTURER_DELETE_FAIL = 'MANUFACTURER_DELETE_FAIL'

export const MANUFACTURER_DETAILS_REQUEST = 'MANUFACTURER_DETAILS_REQUEST'
export const MANUFACTURER_DETAILS_SUCCESS = 'MANUFACTURER_DETAILS_SUCCESS'
export const MANUFACTURER_DETAILS_FAIL = 'MANUFACTURER_DETAILS_FAIL'

export const MANUFACTURER_UPDATE_REQUEST = 'MANUFACTURER_UPDATE_REQUEST'
export const MANUFACTURER_UPDATE_SUCCESS = 'MANUFACTURER_UPDATE_SUCCESS'
export const MANUFACTURER_UPDATE_FAIL = 'MANUFACTURER_UPDATE_FAIL'
export const MANUFACTURER_UPDATE_RESET = 'MANUFACTURER_UPDATE_RESET'


export const SUPPLIER_LIST_REQUEST = 'SUPPLIER_LIST_REQUEST'
export const SUPPLIER_LIST_SUCCESS = 'SUPPLIER_LIST_SUCCESS'
export const SUPPLIER_LIST_FAIL = 'SUPPLIER_LIST_FAIL'

export const SUPPLIER_CREATE_REQUEST = 'SUPPLIER_CREATE_REQUEST'
export const SUPPLIER_CREATE_SUCCESS = 'SUPPLIER_CREATE_SUCCESS'
export const SUPPLIER_CREATE_FAIL = 'SUPPLIER_CREATE_FAIL'
export const SUPPLIER_CREATE_RESET = 'SUPPLIER_CREATE_RESET'

export const SUPPLIER_DELETE_REQUEST = 'SUPPLIER_DELETE_REQUEST'
export const SUPPLIER_DELETE_SUCCESS = 'SUPPLIER_DELETE_SUCCESS'
export const SUPPLIER_DELETE_FAIL = 'SUPPLIER_DELETE_FAIL'
export const SUPPLIER_DELETE_RESET = 'SUPPLIER_DELETE_RESE'

export const SUPPLIER_DETAILS_REQUEST = 'SUPPLIER_DETAILS_REQUEST'
export const SUPPLIER_DETAILS_SUCCESS = 'SUPPLIER_DETAILS_SUCCESS'
export const SUPPLIER_DETAILS_FAIL = 'SUPPLIER_DETAILS_FAIL'

export const SUPPLIER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const SUPPLIER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const SUPPLIER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const SUPPLIER_UPDATE_RESET = 'USER_UPDATE_RESET'


export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'