export const SALE_CREATE_REQUEST = 'SALE_CREATE_REQUEST'
export const SALE_CREATE_SUCCESS = 'SALE_CREATE_SUCCESS'
export const SALE_CREATE_FAIL = 'SALE_CREATE_FAIL'
export const SALE_CREATE_RESET = 'SALE_CREATE_RESET'

export const SALE_DETAILS_REQUEST = 'SALE_DETAILS_REQUEST'
export const SALE_DETAILS_SUCCESS = 'SALE_DETAILS_SUCCESS'
export const SALE_DETAILS_FAIL = 'SALE_DETAILS_FAIL'

export const SALE_LIST_MY_REQUEST = 'SALE_LIST_MY_REQUEST'
export const SALE_LIST_MY_SUCCESS = 'SALE_LIST_MY_SUCCESS'
export const SALE_LIST_MY_FAIL = 'SALE_LIST_MY_FAIL'
export const SALE_LIST_MY_RESET = 'SALE_LIST_MY_RESET'

export const SALE_LIST_REQUEST = 'SALE_LIST_REQUEST'
export const SALE_LIST_SUCCESS = 'SALE_LIST_SUCCESS'
export const SALE_LIST_FAIL = 'SALE_LIST_FAIL'

export const SALE_DELETE_REQUEST = 'SALE_DELETE_REQUEST'
export const SALE_DELETE_SUCCESS = 'SALE_DELETE_SUCCESS'
export const SALE_DELETE_FAIL = 'SALE_DELETE_FAIL'
export const SALE_DELETE_RESET = 'SALE_DELETE_RESET'

export const SALE_UPDATE_REQUEST = 'SALE_UPDATE_REQUEST'
export const SALE_UPDATE_SUCCESS = 'SALE_UPDATE_SUCCESS'
export const SALE_UPDATE_FAIL = 'SALE_UPDATE_FAIL'
export const SALE_UPDATE_RESET = 'SALE_UPDATE_RESET'

export const SALE_SUBMIT_REQUEST = 'SALE_SUBMIT_REQUEST'
export const SALE_SUBMIT_SUCCESS = 'SALE_SUBMIT_SUCCESS'
export const SALE_SUBMIT_FAIL = 'SALE_SUBMIT_FAIL'
export const SALE_SUBMIT_RESET = 'SALE_SUBMIT_RESET'

export const SALE_SUBMITTED_LIST_REQUEST = 'SALE_SUBMITTED_LIST_REQUEST'
export const SALE_SUBMITTED_LIST_SUCCESS = 'SALE_SUBMITTED_LIST_SUCCESS'
export const SALE_SUBMITTED_LIST_FAIL = 'SALE_SUBMITTED_LIST_FAIL'

export const SALE_PAY_REQUEST = 'SALE_PAY_REQUEST'
export const SALE_PAY_SUCCESS = 'SALE_PAY_SUCCESS'
export const SALE_PAY_FAIL = 'SALE_PAY_FAIL'
export const SALE_PAY_RESET = 'SALE_PAY_RESET'

export const SALE_BILL_REQUEST = 'SALE_BILL_REQUEST'
export const SALE_BILL_SUCCESS = 'SALE_BILL_SUCCESS'
export const SALE_BILL_FAIL = 'SALE_BILL_FAIL'
export const SALE_BILL_RESET = 'SALE_BILL_RESET'

export const SALE_BILLED_LIST_REQUEST = 'SALE_BILLED_LIST_REQUEST'
export const SALE_BILLED_LIST_SUCCESS = 'SALE_BILLED_LIST_SUCCESS'
export const SALE_BILLED_LIST_FAIL = 'SALE_BILLED_LIST_FAIL'

export const SALE_COLLECT_REQUEST = 'SALE_COLLECT_REQUEST'
export const SALE_COLLECT_SUCCESS = 'SALE_COLLECT_SUCCESS'
export const SALE_COLLECT_FAIL = 'SALE_COLLECT_FAIL'
export const SALE_COLLECT_RESET = 'SALE_COLLECT_RESET'

export const SALE_COLLECTED_LIST_REQUEST = 'SALE_COLLECTED_LIST_REQUEST'
export const SALE_COLLECTED_LIST_SUCCESS = 'SALE_COLLECTED_LIST_SUCCESS'
export const SALE_COLLECTED_LIST_FAIL = 'SALE_COLLECTED_LIST_FAIL'

export const SALE_DELIVER_REQUEST = 'SALE_DELIVER_REQUEST'
export const SALE_DELIVER_SUCCESS = 'SALE_DELIVER_SUCCESS'
export const SALE_DELIVER_FAIL = 'SALE_DELIVER_FAIL'
export const SALE_DELIVER_RESET = 'SALE_DELIVER_RESET'

export const SALE_DELIVERED_LIST_REQUEST = 'SALE_DELIVERED_LIST_REQUEST'
export const SALE_DELIVERED_LIST_SUCCESS = 'SALE_DELIVERED_LIST_SUCCESS'
export const SALE_DELIVERED_LIST_FAIL = 'SALE_DELIVERED_LIST_FAIL'

export const SALE_SB_REQUEST = 'SALE_SB_REQUEST'
export const SALE_SB_SUCCESS = 'SALE_SB_SUCCESS'
export const SALE_SB_FAIL = 'SALE_SB_FAIL'
export const SALE_SB_RESET = 'SALE_SB_RESET'

export const SALE_REJECT_REQUEST = 'SALE_REJECT_REQUEST'
export const SALE_REJECT_SUCCESS = 'SALE_REJECT_SUCCESS'
export const SALE_REJECT_FAIL = 'SALE_REJECT_FAIL'
export const SALE_REJECT_RESET = 'SALE_REJECT_RESET'


export const SALE_CARD_PAY_REQUEST = 'SALE_CARD_PAY_REQUEST'
export const SALE_CARD_PAY_SUCCESS = 'SALE_CARD_PAY_SUCCESS'
export const SALE_CARD_PAY_FAIL = 'SALE_CARD_PAY_FAIL'
export const SALE_CARD_PAY_RESET = 'SALE_CARD_PAY_RESET'


export const SALE_PAID_LIST_REQUEST = 'SALE_PAID_LIST_REQUEST'
export const SALE_PAID_LIST_SUCCESS = 'SALE_PAID_LIST_SUCCESS'
export const SALE_PAID_LIST_FAIL = 'SALE_PAID_LIST_FAIL'